# 🐳 Tanzen Musik Website - Ready to Deploy
# Einfach "docker-compose up -d" ausführen und läuft!

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    volumes:
      # Persistente Daten - diese Ordner werden automatisch erstellt
      - ./data:/app/data
      - ./uploads:/app/public/uploads
      - ./temp:/app/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tanzen-musik.rule=Host(`your-domain.com`)"
      - "traefik.http.services.tanzen-musik.loadbalancer.server.port=3000"
